// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlgen_example

type Job struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Location    string `json:"location"`
	CreatedBy   string `json:"createdBy"`
}

type NewJob struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Location    string `json:"location"`
	CreatedBy   string `json:"createdBy"`
}
